// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqN1cvFIU6MEx-4BiXccuBuRVQW9AkpUw',
    appId: '1:754254436761:web:d7da3270fc0f83bbe69b08',
    databaseURL: "https://auvo-mvp-default-rtdb.firebaseio.com",
    messagingSenderId: '754254436761',
    projectId: 'auvo-mvp',
    authDomain: 'auvo-mvp.firebaseapp.com',
    storageBucket: 'auvo-mvp.appspot.com',
    measurementId: 'G-PPMJJ3TM1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3g0eVLPi1ekDj_KkwJPUG38mfKVr8ioc',
    appId: '1:754254436761:android:d62697044d93ee5fe69b08',
    messagingSenderId: '754254436761',
    projectId: 'auvo-mvp',
    storageBucket: 'auvo-mvp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCczGJJU0Ug-zAhDvYm6d8s1uNGrYzYh0w',
    appId: '1:754254436761:ios:c14c02b3256c7ffbe69b08',
    messagingSenderId: '754254436761',
    projectId: 'auvo-mvp',
    storageBucket: 'auvo-mvp.appspot.com',
    iosBundleId: 'com.auvo.auvoMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCczGJJU0Ug-zAhDvYm6d8s1uNGrYzYh0w',
    appId: '1:754254436761:ios:9d85697482b93772e69b08',
    messagingSenderId: '754254436761',
    projectId: 'auvo-mvp',
    storageBucket: 'auvo-mvp.appspot.com',
    iosBundleId: 'com.auvo.auvoMvp.RunnerTests',
  );
}
